baseURL = "/"
title = "PTP: Cheatsheet"
theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowToc = true
TocOpen = true

[params.homeInfoParams]
Title = "PTP: Cheatsheet"
Content = " Study notes and tools for networking, web app hacking, penetration testing, and basic programming (C++, Python). Includes HTTP/S, cookies, SQLi, XSS, enumeration, nmap usage, and more."