Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.hostname = "kali-lab"

  config.vm.provider :libvirt do |v|
    v.memory = 8192
    v.cpus = 4
    v.management_network_device = "virbr0"
    #v.memorybacking :access, mode: 'shared'
    v.video_type = "vga"
    v.video_vram = 16384
    v.graphics_type = "spice"
    v.channel :type => 'spicevmc', :target_type => 'virtio', :target_name => 'com.redhat.spice.0'
  end

  # Zsh configs
  config.vm.provision "file", source: "zsh_customizations.zshrc", destination: "/tmp/zsh_customizations.zshrc"

  # Provision guest
  config.vm.provision "shell", path: "provision.sh"
end
